global:
  scrape_interval: 10s
  evaluation_interval: 30s

scrape_configs:
  - job_name: redis-streams-monitor
    honor_labels: true
    static_configs:
      - targets: ["redis-streams-monitor:3000"]
